In [1]:
import pandas as pd

In [21]:
import sklearn

In [2]:
matches = pd.read_csv("matches.csv", index_col=0)

In [3]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,Match Report,NaN,17.0,8.0,13.9,0.0,0,0,2024,Manchester City
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,Match Report,NaN,14.0,4.0,17.9,0.0,0,0,2024,Manchester City
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,Match Report,NaN,29.0,9.0,17.3,2.0,0,1,2024,Manchester City
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,Match Report,NaN,6.0,4.0,14.8,0.0,1,1,2024,Manchester City
6,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3,1,West Ham,...,Match Report,NaN,29.0,13.0,16.4,1.0,0,0,2024,Manchester City

In [4]:
matches.shape

(1520, 27)

In [6]:
38 * 20 * 2

1520

In [ ]:
#number of matches OK (no missing data)

In [7]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf                int64
ga                int64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk                int64
pkatt             int64
season            int64
team             object
dtype: object

In [8]:
del matches["comp"]

In [9]:
del matches["notes"]

In [10]:
matches["date"] = pd.to_datetime(matches["date"])

In [11]:
matches["target"] = (matches["result"] == "W").astype("int")

In [12]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,match report,sh,sot,dist,fk,pk,pkatt,season,team,target
1,2023-08-11,20:00,Matchweek 1,Fri,Away,W,3,0,Burnley,1.9,...,Match Report,17.0,8.0,13.9,0.0,0,0,2024,Manchester City,1
3,2023-08-19,20:00,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,1.0,...,Match Report,14.0,4.0,17.9,0.0,0,0,2024,Manchester City,1
4,2023-08-27,14:00,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,3.5,...,Match Report,29.0,9.0,17.3,2.0,0,1,2024,Manchester City,1
5,2023-09-02,15:00,Matchweek 4,Sat,Home,W,5,1,Fulham,2.2,...,Match Report,6.0,4.0,14.8,0.0,1,1,2024,Manchester City,1
6,2023-09-16,15:00,Matchweek 5,Sat,Away,W,3,1,West Ham,3.6,...,Match Report,29.0,13.0,16.4,1.0,0,0,2024,Manchester City,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2023-04-30,14:00,Matchweek 34,Sun,Away,L,1,3,Newcastle Utd,0.8,...,Match Report,4.0,3.0,17.3,0.0,0,0,2023,Southampton,0
43,2023-05-08,20:00,Matchweek 35,Mon,Away,L,3,4,Nott'ham Forest,3.1,...,Match Report,18.0,4.0,14.0,0.0,1,1,2023,Southampton,0
44,2023-05-13,15:00,Matchweek 36,Sat,Home,L,0,2,Fulham,0.4,...,Match Report,5.0,1.0,24.2,0.0,0,0,2023,Southampton,0
45,2023-05-21,14:00,Matchweek 37,Sun,Away,L,1,3,Brighton,0.6,...,Match Report,5.0,1.0,13.8,1.0,0,0,2023,Southampton,0
46,2023-05-28,16:30,Matchweek 38,Sun,Home,D,4,4,Liverpool,1.8,...,Match Report,15.0,10.0,17.5,1.0,0,0,2023,Southampton,0

In [13]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [14]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [15]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [16]:
matches["day_code"] = matches["date"].dt.dayofweek

In [17]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
1,2023-08-11,20:00,Matchweek 1,Fri,Away,W,3,0,Burnley,1.9,...,0.0,0,0,2024,Manchester City,1,0,5,20,4
3,2023-08-19,20:00,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,1.0,...,0.0,0,0,2024,Manchester City,1,1,16,20,5
4,2023-08-27,14:00,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,3.5,...,2.0,0,1,2024,Manchester City,1,0,18,14,6
5,2023-09-02,15:00,Matchweek 4,Sat,Home,W,5,1,Fulham,2.2,...,0.0,1,1,2024,Manchester City,1,1,9,15,5
6,2023-09-16,15:00,Matchweek 5,Sat,Away,W,3,1,West Ham,3.6,...,1.0,0,0,2024,Manchester City,1,0,21,15,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2023-04-30,14:00,Matchweek 34,Sun,Away,L,1,3,Newcastle Utd,0.8,...,0.0,0,0,2023,Southampton,0,0,16,14,6
43,2023-05-08,20:00,Matchweek 35,Mon,Away,L,3,4,Nott'ham Forest,3.1,...,0.0,1,1,2023,Southampton,0,0,17,20,0
44,2023-05-13,15:00,Matchweek 36,Sat,Home,L,0,2,Fulham,0.4,...,0.0,0,0,2023,Southampton,0,1,9,15,5
45,2023-05-21,14:00,Matchweek 37,Sun,Away,L,1,3,Brighton,0.6,...,1.0,0,0,2023,Southampton,0,0,4,14,6
46,2023-05-28,16:30,Matchweek 38,Sun,Home,D,4,4,Liverpool,1.8,...,1.0,0,0,2023,Southampton,0,1,12,16,6

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [24]:
train = matches[matches["date"] < '2024-01-01']

In [25]:
test = matches[matches["date"] > '2024-01-01']

In [26]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [27]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [28]:
preds = rf.predict(test[predictors])

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
error = accuracy_score(test["target"], preds)

In [31]:
error

0.6229508196721312

In [32]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [33]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0   1
actual
0          168  61
1           77  60

In [34]:
from sklearn.metrics import precision_score

In [35]:
precision_score(test["target"], preds)

np.float64(0.49586776859504134)

In [36]:
grouped_matches = matches.groupby("team")

In [37]:
group = grouped_matches.get_group("Manchester City").sort_values("date")

In [38]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [39]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]

In [40]:
new_cols = [f"{c}_rolling" for c in cols]

In [42]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [43]:
rolling_averages(group, cols, new_cols)

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2022-08-27,15:00,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,2.2,...,15,5,3.000000,1.000000,17.666667,6.000000,17.466667,0.666667,0.333333,0.333333
5,2022-08-31,19:30,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,3.3,...,19,2,3.666667,1.666667,19.333333,7.333333,15.933333,0.333333,0.000000,0.000000
6,2022-09-03,17:30,Matchweek 6,Sat,Away,D,1,1,Aston Villa,2.1,...,17,5,4.333333,1.666667,18.666667,8.000000,15.033333,0.333333,0.000000,0.000000
9,2022-09-17,12:30,Matchweek 8,Sat,Away,W,3,0,Wolves,1.1,...,12,5,3.666667,1.000000,16.000000,6.000000,15.233333,0.333333,0.000000,0.000000
10,2022-10-02,14:00,Matchweek 9,Sun,Home,W,6,3,Manchester Utd,3.2,...,14,6,3.333333,0.333333,15.333333,6.666667,17.000000,0.333333,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,2024-04-28,16:30,Matchweek 35,Sun,Away,W,2,0,Nott'ham Forest,0.9,...,16,6,4.333333,1.000000,22.666667,8.666667,16.666667,0.333333,0.333333,0.333333
52,2024-05-04,17:30,Matchweek 36,Sat,Home,W,5,1,Wolves,3.7,...,17,5,3.666667,0.333333,20.333333,7.666667,17.533333,0.666667,0.333333,0.333333
53,2024-05-11,12:30,Matchweek 37,Sat,Away,W,4,0,Fulham,3.2,...,12,5,3.666667,0.333333,14.333333,7.000000,17.000000,0.666667,0.666667,0.666667
54,2024-05-14,20:00,Matchweek 34,Tue,Away,W,2,0,Tottenham,2.4,...,20,1,3.666667,0.333333,14.666667,7.666667,17.200000,0.333333,1.000000,1.000000
55,2024-05-19,16:00,Matchweek 38,Sun,Home,W,3,1,West Ham,1.9,...,16,6,3.666667,0.333333,13.333333,7.333333,15.800000,0.000000,1.333333,1.333333

In [46]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

C:\Users\User\AppData\Local\Temp\ipykernel_6912\4052147919.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [47]:
matches_rolling

                                 date   time         round  day venue result  \
team
Arsenal                 3  2022-08-27  17:30   Matchweek 4  Sat  Home      W
                        4  2022-08-31  19:30   Matchweek 5  Wed  Home      W
                        5  2022-09-04  16:30   Matchweek 6  Sun  Away      L
                        7  2022-09-18  12:00   Matchweek 8  Sun  Away      W
                        8  2022-10-01  12:30   Matchweek 9  Sat  Home      W
...                               ...    ...           ...  ...   ...    ...
Wolverhampton Wanderers 40 2024-04-24  19:45  Matchweek 29  Wed  Home      L
                        41 2024-04-27  15:00  Matchweek 35  Sat  Home      W
                        42 2024-05-04  17:30  Matchweek 36  Sat  Away      L
                        43 2024-05-11  15:00  Matchweek 37  Sat  Home      L
                        44 2024-05-19  16:00  Matchweek 38  Sun  Away      L

                            gf  ga         opponent   xg  ...  hour  day_code  \
team                                                      ...
Arsenal                 3    2   1           Fulham  2.6  ...    17         5
                        4    2   1      Aston Villa  2.4  ...    19         2
                        5    1   3   Manchester Utd  1.3  ...    16         6
                        7    3   0        Brentford  1.5  ...    12         6
                        8    3   1        Tottenham  2.4  ...    12         5
...                         ..  ..              ...  ...  ...   ...       ...
Wolverhampton Wanderers 40   0   1      Bournemouth  0.5  ...    19         2
                        41   2   1       Luton Town  1.2  ...    15         5
                        42   1   5  Manchester City  0.3  ...    17         5
                        43   1   3   Crystal Palace  1.6  ...    15         5
                        44   0   2        Liverpool  0.5  ...    16         6

                            gf_rolling ga_rolling sh_rolling sot_rolling  \
team
Arsenal                 3     3.000000   0.666667  14.333333    5.000000
                        4     3.000000   1.000000  18.333333    7.000000
                        5     2.333333   0.666667  19.333333    7.333333
                        7     1.666667   1.666667  20.000000    6.333333
                        8     2.000000   1.333333  17.000000    6.000000
...                                ...        ...        ...         ...
Wolverhampton Wanderers 40    1.000000   2.000000   9.666667    4.000000
                        41    0.666667   1.666667  10.333333    3.333333
                        42    0.666667   1.333333  11.000000    4.000000
                        43    1.000000   2.333333  10.000000    3.333333
                        44    1.333333   3.000000   9.666667    4.666667

                           dist_rolling  fk_rolling  pk_rolling  pkatt_rolling
team
Arsenal                 3     14.133333    0.333333    0.000000       0.000000
                        4     14.433333    0.333333    0.000000       0.000000
                        5     15.533333    0.666667    0.000000       0.000000
                        7     16.800000    1.000000    0.000000       0.000000
                        8     17.700000    0.666667    0.000000       0.000000
...                                 ...         ...         ...            ...
Wolverhampton Wanderers 40    20.533333    0.333333    0.333333       0.333333
                        41    18.766667    0.000000    0.000000       0.000000
                        42    19.666667    0.000000    0.000000       0.000000
                        43    15.966667    0.000000    0.000000       0.000000
                        44    14.133333    0.000000    0.000000       0.000000

[1451 rows x 38 columns]

In [48]:
matches_rolling = matches_rolling.droplevel('team')

In [49]:
matches_rolling

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
3,2022-08-27,17:30,Matchweek 4,Sat,Home,W,2,1,Fulham,2.6,...,17,5,3.000000,0.666667,14.333333,5.000000,14.133333,0.333333,0.000000,0.000000
4,2022-08-31,19:30,Matchweek 5,Wed,Home,W,2,1,Aston Villa,2.4,...,19,2,3.000000,1.000000,18.333333,7.000000,14.433333,0.333333,0.000000,0.000000
5,2022-09-04,16:30,Matchweek 6,Sun,Away,L,1,3,Manchester Utd,1.3,...,16,6,2.333333,0.666667,19.333333,7.333333,15.533333,0.666667,0.000000,0.000000
7,2022-09-18,12:00,Matchweek 8,Sun,Away,W,3,0,Brentford,1.5,...,12,6,1.666667,1.666667,20.000000,6.333333,16.800000,1.000000,0.000000,0.000000
8,2022-10-01,12:30,Matchweek 9,Sat,Home,W,3,1,Tottenham,2.4,...,12,5,2.000000,1.333333,17.000000,6.000000,17.700000,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,2024-04-24,19:45,Matchweek 29,Wed,Home,L,0,1,Bournemouth,0.5,...,19,2,1.000000,2.000000,9.666667,4.000000,20.533333,0.333333,0.333333,0.333333
41,2024-04-27,15:00,Matchweek 35,Sat,Home,W,2,1,Luton Town,1.2,...,15,5,0.666667,1.666667,10.333333,3.333333,18.766667,0.000000,0.000000,0.000000
42,2024-05-04,17:30,Matchweek 36,Sat,Away,L,1,5,Manchester City,0.3,...,17,5,0.666667,1.333333,11.000000,4.000000,19.666667,0.000000,0.000000,0.000000
43,2024-05-11,15:00,Matchweek 37,Sat,Home,L,1,3,Crystal Palace,1.6,...,15,5,1.000000,2.333333,10.000000,3.333333,15.966667,0.000000,0.000000,0.000000
44,2024-05-19,16:00,Matchweek 38,Sun,Away,L,0,2,Liverpool,0.5,...,16,6,1.333333,3.000000,9.666667,4.666667,14.133333,0.000000,0.000000,0.000000

In [50]:
matches_rolling.index = range(matches_rolling.shape[0])

In [51]:
matches_rolling

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2022-08-27,17:30,Matchweek 4,Sat,Home,W,2,1,Fulham,2.6,...,17,5,3.000000,0.666667,14.333333,5.000000,14.133333,0.333333,0.000000,0.000000
1,2022-08-31,19:30,Matchweek 5,Wed,Home,W,2,1,Aston Villa,2.4,...,19,2,3.000000,1.000000,18.333333,7.000000,14.433333,0.333333,0.000000,0.000000
2,2022-09-04,16:30,Matchweek 6,Sun,Away,L,1,3,Manchester Utd,1.3,...,16,6,2.333333,0.666667,19.333333,7.333333,15.533333,0.666667,0.000000,0.000000
3,2022-09-18,12:00,Matchweek 8,Sun,Away,W,3,0,Brentford,1.5,...,12,6,1.666667,1.666667,20.000000,6.333333,16.800000,1.000000,0.000000,0.000000
4,2022-10-01,12:30,Matchweek 9,Sat,Home,W,3,1,Tottenham,2.4,...,12,5,2.000000,1.333333,17.000000,6.000000,17.700000,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1446,2024-04-24,19:45,Matchweek 29,Wed,Home,L,0,1,Bournemouth,0.5,...,19,2,1.000000,2.000000,9.666667,4.000000,20.533333,0.333333,0.333333,0.333333
1447,2024-04-27,15:00,Matchweek 35,Sat,Home,W,2,1,Luton Town,1.2,...,15,5,0.666667,1.666667,10.333333,3.333333,18.766667,0.000000,0.000000,0.000000
1448,2024-05-04,17:30,Matchweek 36,Sat,Away,L,1,5,Manchester City,0.3,...,17,5,0.666667,1.333333,11.000000,4.000000,19.666667,0.000000,0.000000,0.000000
1449,2024-05-11,15:00,Matchweek 37,Sat,Home,L,1,3,Crystal Palace,1.6,...,15,5,1.000000,2.333333,10.000000,3.333333,15.966667,0.000000,0.000000,0.000000
1450,2024-05-19,16:00,Matchweek 38,Sun,Away,L,0,2,Liverpool,0.5,...,16,6,1.333333,3.000000,9.666667,4.666667,14.133333,0.000000,0.000000,0.000000

In [52]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2024-01-01']
    test = data[data["date"] > '2024-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [53]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [56]:
error

np.float64(0.5447154471544715)

In [57]:
combined

      actual  predicted
55         1          1
56         1          1
57         1          1
58         1          0
59         1          0
...      ...        ...
1446       0          0
1447       1          0
1448       0          0
1449       0          0
1450       0          0

[366 rows x 2 columns]

In [58]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [59]:
combined.head(10)

    actual  predicted       date     team         opponent result
55       1          1 2024-01-20  Arsenal   Crystal Palace      W
56       1          1 2024-01-30  Arsenal  Nott'ham Forest      W
57       1          1 2024-02-04  Arsenal        Liverpool      W
58       1          0 2024-02-11  Arsenal         West Ham      W
59       1          0 2024-02-17  Arsenal          Burnley      W
60       1          1 2024-02-24  Arsenal    Newcastle Utd      W
61       1          1 2024-03-04  Arsenal    Sheffield Utd      W
62       1          1 2024-03-09  Arsenal        Brentford      W
63       0          0 2024-03-31  Arsenal  Manchester City      D
64       1          1 2024-04-03  Arsenal       Luton Town      W

In [60]:
combined

,actual,predicted,date,team,opponent,result
55,1,1,2024-01-20,Arsenal,Crystal Palace,W
56,1,1,2024-01-30,Arsenal,Nott'ham Forest,W
57,1,1,2024-02-04,Arsenal,Liverpool,W
58,1,0,2024-02-11,Arsenal,West Ham,W
59,1,0,2024-02-17,Arsenal,Burnley,W
...,...,...,...,...,...,...
1446,0,0,2024-04-24,Wolverhampton Wanderers,Bournemouth,L
1447,1,0,2024-04-27,Wolverhampton Wanderers,Luton Town,W
1448,0,0,2024-05-04,Wolverhampton Wanderers,Manchester City,L
1449,0,0,2024-05-11,Wolverhampton Wanderers,Crystal Palace,L
1450,0,0,2024-05-19,Wolverhampton Wanderers,Liverpool,L

In [69]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves", "Nott'ham Forest": "Nottingham Forest"} 
mapping = MissingDict(**map_values)

In [70]:
mapping["Arsenal"]

'Arsenal'

In [71]:
mapping["Nott'ham Forest"]

'Nottingham Forest'

In [72]:
combined["new_team"] = combined["team"].map(mapping)

In [73]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [74]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,1,1,2024-01-20,Arsenal,Crystal Palace,W,Arsenal,0,0,Crystal Palace,Arsenal,L,Crystal Palace
1,1,1,2024-01-30,Arsenal,Nott'ham Forest,W,Arsenal,0,0,Nottingham Forest,Arsenal,L,Nottingham Forest
2,1,1,2024-02-04,Arsenal,Liverpool,W,Arsenal,0,0,Liverpool,Arsenal,L,Liverpool
3,1,0,2024-02-11,Arsenal,West Ham,W,Arsenal,0,0,West Ham United,Arsenal,L,West Ham
4,1,0,2024-02-17,Arsenal,Burnley,W,Arsenal,0,0,Burnley,Arsenal,L,Burnley
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,0,0,2024-04-24,Wolverhampton Wanderers,Bournemouth,L,Wolves,1,0,Bournemouth,Wolves,W,Bournemouth
326,1,0,2024-04-27,Wolverhampton Wanderers,Luton Town,W,Wolves,0,0,Luton Town,Wolves,L,Luton Town
327,0,0,2024-05-04,Wolverhampton Wanderers,Manchester City,L,Wolves,1,1,Manchester City,Wolves,W,Manchester City
328,0,0,2024-05-11,Wolverhampton Wanderers,Crystal Palace,L,Wolves,1,1,Crystal Palace,Wolves,W,Crystal Palace
329,0,0,2024-05-19,Wolverhampton Wanderers,Liverpool,L,Wolves,1,1,Liverpool,Wolves,W,Liverpool

In [75]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

actual_x
1    59
0    41
Name: count, dtype: int64

In [76]:
59 / 100

0.59